// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignRolePermissionsReq struct {
	RoleID        string   `path:"role_id" validate:"required"`
	PermissionIDs []string `json:"permission_ids" validate:"required"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password" validate:"required"`
	NewPassword string `json:"new_password" validate:"required"`
}

type CreatePermissionReq struct {
	PermissionID       string `json:"permission_id" validate:"required"`
	PermissionName     string `json:"permission_name" validate:"required"`
	PermissionCode     string `json:"permission_code" validate:"required"`
	PermissionType     string `json:"permission_type" validate:"required"`
	ParentPermissionID string `json:"parent_permission_id,omitempty"`
}

type CreatePermissionResp struct {
	PermissionID string `json:"permission_id"`
}

type CreateRoleReq struct {
	RoleName string `json:"role_name" validate:"required"`
	RoleDesc string `json:"role_desc,omitempty"`
}

type CreateRoleResp struct {
	RoleID string `json:"role_id"`
}

type CreateUserReq struct {
	UserName           string `json:"user_name" validate:"required"`
	RealName           string `json:"real_name" validate:"required"`
	Password           string `json:"password" validate:"required"`
	RoleID             string `json:"role_id" validate:"required"`
	Department         string `json:"department,omitempty"`
	Position           string `json:"position,omitempty"`
	ContactPhone       string `json:"contact_phone,omitempty"`
	UserStatus         string `json:"user_status" validate:"required"`
	PasswordExpireTime string `json:"password_expire_time,omitempty"`
}

type CreateUserResp struct {
	UserID string `json:"user_id"`
}

type DeletePermissionReq struct {
	PermissionID string `path:"permission_id" validate:"required"`
}

type DeleteRoleReq struct {
	RoleID string `path:"role_id" validate:"required"`
}

type DeleteUserReq struct {
	UserID string `path:"user_id" validate:"required"`
}

type GetCurrentUserPermissionsResp struct {
	Permissions []PermissionInfo `json:"permissions"`
}

type GetPermissionReq struct {
	PermissionID string `path:"permission_id" validate:"required"`
}

type GetPermissionResp struct {
	PermissionInfo PermissionInfo `json:"permission_info"`
}

type GetPermissionTreeReq struct {
	PermissionType string `form:"permission_type,optional"`
}

type GetPermissionTreeResp struct {
	Tree []PermissionInfo `json:"tree"`
}

type GetRolePermissionsReq struct {
	RoleID string `path:"role_id" validate:"required"`
}

type GetRolePermissionsResp struct {
	Permissions []PermissionInfo `json:"permissions"`
}

type GetRoleReq struct {
	RoleID string `path:"role_id" validate:"required"`
}

type GetRoleResp struct {
	RoleInfo RoleInfo `json:"role_info"`
}

type GetUserReq struct {
	UserID string `path:"user_id" validate:"required"`
}

type GetUserResp struct {
	UserInfo UserInfo `json:"user_info"`
}

type ListPermissionsReq struct {
	Page           int64  `form:"page,default=1"`
	PageSize       int64  `form:"page_size,default=10"`
	PermissionName string `form:"permission_name,optional"`
	PermissionType string `form:"permission_type,optional"`
}

type ListPermissionsResp struct {
	Total int64            `json:"total"`
	List  []PermissionInfo `json:"list"`
}

type ListRolesReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	RoleName string `form:"role_name,optional"`
}

type ListRolesResp struct {
	Total int64      `json:"total"`
	List  []RoleInfo `json:"list"`
}

type ListUsersReq struct {
	Page       int64  `form:"page,default=1"`
	PageSize   int64  `form:"page_size,default=10"`
	UserName   string `form:"user_name,optional"`
	RealName   string `form:"real_name,optional"`
	RoleID     string `form:"role_id,optional"`
	UserStatus string `form:"user_status,optional"`
	Department string `form:"department,optional"`
}

type ListUsersResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}

type LoginReq struct {
	UserName string `json:"user_name" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token,omitempty"`
	UserInfo     UserInfo `json:"user_info"`
}

type PermissionInfo struct {
	PermissionID       string `json:"permission_id"`
	PermissionName     string `json:"permission_name"`
	PermissionCode     string `json:"permission_code"`
	PermissionType     string `json:"permission_type"`
	ParentPermissionID string `json:"parent_permission_id,omitempty"`
	CreateTime         string `json:"create_time"`
	UpdateTime         string `json:"update_time"`
	DeletedAt          string `json:"deleted_at"`
}

type ResetPasswordReq struct {
	UserID      string `path:"user_id" validate:"required"`
	NewPassword string `json:"new_password" validate:"required"`
}

type Response struct {
	Code uint32      `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type RoleInfo struct {
	RoleID      string           `json:"role_id"`
	RoleName    string           `json:"role_name"`
	RoleDesc    string           `json:"role_desc,omitempty"`
	CreateTime  string           `json:"create_time"`
	UpdateTime  string           `json:"update_time"`
	Permissions []PermissionInfo `json:"permissions,omitempty"` // 权限ID列表
}

type UpdatePermissionReq struct {
	PermissionID       string `path:"permission_id" validate:"required"`
	PermissionName     string `json:"permission_name,omitempty"`
	PermissionCode     string `json:"permission_code,omitempty"`
	PermissionType     string `json:"permission_type,omitempty"`
	ParentPermissionID string `json:"parent_permission_id,omitempty"`
}

type UpdateRoleReq struct {
	RoleID   string `path:"role_id" validate:"required"`
	RoleName string `json:"role_name,omitempty"`
	RoleDesc string `json:"role_desc,omitempty"`
}

type UpdateUserReq struct {
	UserID             string `path:"user_id" validate:"required"`
	RealName           string `json:"real_name,omitempty"`
	RoleID             string `json:"role_id,omitempty"`
	Department         string `json:"department,omitempty"`
	Position           string `json:"position,omitempty"`
	ContactPhone       string `json:"contact_phone,omitempty"`
	UserStatus         string `json:"user_status,omitempty"`
	PasswordExpireTime string `json:"password_expire_time,omitempty"`
}

type UserInfo struct {
	UserID             string `json:"user_id"`
	UserName           string `json:"user_name"`
	RealName           string `json:"real_name"`
	RoleID             string `json:"role_id"`
	RoleName           string `json:"role_name,omitempty"`
	Department         string `json:"department,omitempty"`
	Position           string `json:"position,omitempty"`
	ContactPhone       string `json:"contact_phone,omitempty"`
	UserStatus         string `json:"user_status"`
	LastLoginTime      string `json:"last_login_time,omitempty"`
	PasswordExpireTime string `json:"password_expire_time"`
	CreateTime         string `json:"create_time"`
	UpdateTime         string `json:"update_time"`
}
