// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "WMSS/user/api/internal/handler/auth"
	permission "WMSS/user/api/internal/handler/permission"
	role "WMSS/user/api/internal/handler/role"
	user "WMSS/user/api/internal/handler/user"
	"WMSS/user/api/internal/middleware" // 导入你写的自定义 JWT 中间件包
	"WMSS/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 登录接口（公开接口，无需授权）- 保持不变
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	// 1. 权限相关接口：替换为自定义 JWT 中间件
	server.AddRoutes(
		rest.WithMiddlewares(
			// 关键修改：用你的自定义 JWT 中间件，传入配置中的 JWT 密钥
			[]rest.Middleware{middleware.JwtAuthMiddleware(serverCtx.Config.Auth.AccessSecret)},
			[]rest.Route{
				{Method: http.MethodPost, Path: "/create", Handler: permission.CreatePermissionHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/detail/:permission_id", Handler: permission.GetPermissionHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/list", Handler: permission.ListPermissionsHandler(serverCtx)},
				{Method: http.MethodDelete, Path: "/remove/:permission_id", Handler: permission.DeletePermissionHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/tree", Handler: permission.GetPermissionTreeHandler(serverCtx)},
				{Method: http.MethodPut, Path: "/update/:permission_id", Handler: permission.UpdatePermissionHandler(serverCtx)},
			}...,
		),
		// 关键修改：删除原有的 rest.WithJwt()（避免和自定义中间件重复校验）
		rest.WithPrefix("/api/permission"),
	)

	// 2. 角色相关接口：替换为自定义 JWT 中间件（和权限接口修改一致）
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{middleware.JwtAuthMiddleware(serverCtx.Config.Auth.AccessSecret)},
			[]rest.Route{
				{Method: http.MethodPost, Path: "/create", Handler: role.CreateRoleHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/detail/:role_id", Handler: role.GetRoleHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/list", Handler: role.ListRolesHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/permissions/:role_id", Handler: role.AssignRolePermissionsHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/permissions/:role_id", Handler: role.GetRolePermissionsHandler(serverCtx)},
				{Method: http.MethodDelete, Path: "/remove/:role_id", Handler: role.DeleteRoleHandler(serverCtx)},
				{Method: http.MethodPut, Path: "/update/:role_id", Handler: role.UpdateRoleHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/api/role"), // 同样删除 rest.WithJwt()
	)

	// 3. 用户相关接口：替换为自定义 JWT 中间件（和上面修改一致）
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{middleware.JwtAuthMiddleware(serverCtx.Config.Auth.AccessSecret)},
			[]rest.Route{
				{Method: http.MethodPost, Path: "/create", Handler: user.CreateUserHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/current", Handler: user.GetCurrentUserHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/current/permissions", Handler: user.GetCurrentUserPermissionsHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/detail/:user_id", Handler: user.GetUserHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/list", Handler: user.ListUsersHandler(serverCtx)},
				{Method: http.MethodPut, Path: "/password", Handler: user.ChangePasswordHandler(serverCtx)},
				{Method: http.MethodDelete, Path: "/remove/:user_id", Handler: user.DeleteUserHandler(serverCtx)},
				{Method: http.MethodPut, Path: "/reset_password/:user_id", Handler: user.ResetPasswordHandler(serverCtx)},
				{Method: http.MethodPut, Path: "/update/:user_id", Handler: user.UpdateUserHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/api/user"), // 同样删除 rest.WithJwt()
	)
}