// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRolePermissionFieldNames          = builder.RawFieldNames(&SysRolePermission{})
	sysRolePermissionRows                = strings.Join(sysRolePermissionFieldNames, ",")
	sysRolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysRolePermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysRolePermissionModel interface {
		Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRolePermission, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId string, permissionId string) (*SysRolePermission, error)
		Update(ctx context.Context, data *SysRolePermission) error
		Delete(ctx context.Context, id int64) error
		FindPermissionsByRoleId(ctx context.Context, roleId string) ([]string, error)
		InsertBatch(ctx context.Context, data []*SysRolePermission) (sql.Result, error)
	}

	defaultSysRolePermissionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRolePermission struct {
		Id           int64     `db:"id"`            // 关联记录唯一标识，自增
		RoleId       string    `db:"role_id"`       // 角色ID，关联角色表
		PermissionId string    `db:"permission_id"` // 权限ID，关联权限表
		CreateTime   time.Time `db:"create_time"`   // 关联记录创建时间
	}
)

func newSysRolePermissionModel(conn sqlx.SqlConn) *defaultSysRolePermissionModel {
	return &defaultSysRolePermissionModel{
		conn:  conn,
		table: "`sys_role_permission`",
	}
}

func (m *defaultSysRolePermissionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysRolePermissionModel) FindOne(ctx context.Context, id int64) (*SysRolePermission, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysRolePermissionRows, m.table)
	var resp SysRolePermission
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId string, permissionId string) (*SysRolePermission, error) {
	var resp SysRolePermission
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and `permission_id` = ? limit 1", sysRolePermissionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRolePermissionModel) FindPermissionsByRoleId(ctx context.Context, roleId string) ([]string, error) {
	query := fmt.Sprintf(
		"select `permission_id` from %s where `role_id` = ?",
		m.table,
	)

	var permissionIds []string
	err := m.conn.QueryRowsCtx(ctx, &permissionIds, query, roleId)
	if err != nil {
		if err == sqlx.ErrNotFound {
			return []string{}, nil
		}
		return nil, fmt.Errorf("查询角色关联的权限ID失败：%w", err)
	}

	return permissionIds, nil
}

func (m *defaultSysRolePermissionModel) Insert(ctx context.Context, data *SysRolePermission) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysRolePermissionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	return ret, err
}

func (m *defaultSysRolePermissionModel) InsertBatch(ctx context.Context, data []*SysRolePermission) (sql.Result, error) {
	if len(data) == 0 {
		return nil, fmt.Errorf("批量插入数据不能为空")
	}

	// 构建批量插入的 SQL 语句
	// INSERT INTO table (role_id, permission_id) VALUES (?, ?), (?, ?), ...
	valueStrings := make([]string, 0, len(data))
	valueArgs := make([]interface{}, 0, len(data)*2)

	for _, item := range data {
		valueStrings = append(valueStrings, "(?, ?)")
		valueArgs = append(valueArgs, item.RoleId, item.PermissionId)
	}

	query := fmt.Sprintf("insert into %s (%s) values %s",
		m.table,
		sysRolePermissionRowsExpectAutoSet,
		strings.Join(valueStrings, ","))

	ret, err := m.conn.ExecCtx(ctx, query, valueArgs...)
	return ret, err
}

func (m *defaultSysRolePermissionModel) Update(ctx context.Context, newData *SysRolePermission) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysRolePermissionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoleId, newData.PermissionId, newData.Id)
	return err
}

func (m *defaultSysRolePermissionModel) tableName() string {
	return m.table
}
